### PR TITLE
luci-app-cjdns: back off 502 bad gateway for switchping timesouts

### PR DESCRIPTION
**Pull request by wfleurant**
we had a problem with this before act_ping, fixed again with Phil's default admin pinger. Seems to be stable again. I don't see us hitting the 502 gateway aborts. If the admin socket is not there, we're going to hit the act_peers 502 before this. This fixes the undefined found in luci admin latency.

### CODE REVIEW

**Comment by lgierth** [comment]
:shipit:

**Comment by wfleurant** [comment]
When the admin receives a 502 the admin will show pings as undefined... Hmmph.. Take a look at the User/Name column in Safari. Seems to show undefined too. May be the 502 is a red herring? Keep this open 'til both are squashed.
 
name is undefined

**Comment by wfleurant** [comment]
works for me.

**Comment by wfleurant** [comment]
new interface

**Pull request merged**
